### ISSUE TITLE
Loss Function

### ISSUE THREAD

**Issue by AIzhiqing** [pcr-upm/opal23_headpose#7]
Could you please provide the code of Gopal loss？

**Comment by alejandro-cobo** [comment]
Hello, thanks for the interest in our work.

I have uploaded an implementation of our Opal Loss function to src/opal.py and a notebook with an usage example to notebooks/opal_loss.ipynb.

I hope you find it useful.   Please feel free to contact us if you have any questions.

**Comment by AIzhiqing** [comment]
Thank you very much!
